### ISSUE TITLE
Epic: get camera connected and streaming

### ISSUE THREAD

**Issue by DanielHou315** [mh-embed/drone-video-publisher#1]
- [x] setup a pi for developing and testing camera
- [ ] setup opencv stream for auton programs to use
- [ ] We May Need a Node for just streaming the camera to RTSP
- [ ] architect a way to view camera stream via 2.4/5g pi network
